// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0gwADejBnTwKxKUqQTp_ox2nf1NYhfk',
    appId: '1:1091789875933:web:3ac5d3fd8bd0450075c934',
    messagingSenderId: '1091789875933',
    projectId: 'website-192723',
    authDomain: 'website-192723.firebaseapp.com',
    databaseURL: 'https://website-192723.firebaseio.com',
    storageBucket: 'website-192723.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVucOdK7Pr5-r-bh4mBsFNEecrvcL-F7U',
    appId: '1:1091789875933:android:8e2bce71378345fc75c934',
    messagingSenderId: '1091789875933',
    projectId: 'website-192723',
    databaseURL: 'https://website-192723.firebaseio.com',
    storageBucket: 'website-192723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI0B-WAL6BmXTT85fkdaFUAI3VocBQXMA',
    appId: '1:1091789875933:ios:26923341c0aec1aa75c934',
    messagingSenderId: '1091789875933',
    projectId: 'website-192723',
    databaseURL: 'https://website-192723.firebaseio.com',
    storageBucket: 'website-192723.appspot.com',
    iosBundleId: 'com.example.pola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI0B-WAL6BmXTT85fkdaFUAI3VocBQXMA',
    appId: '1:1091789875933:ios:26923341c0aec1aa75c934',
    messagingSenderId: '1091789875933',
    projectId: 'website-192723',
    databaseURL: 'https://website-192723.firebaseio.com',
    storageBucket: 'website-192723.appspot.com',
    iosBundleId: 'com.example.pola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI0gwADejBnTwKxKUqQTp_ox2nf1NYhfk',
    appId: '1:1091789875933:web:c0e171a89bf047e575c934',
    messagingSenderId: '1091789875933',
    projectId: 'website-192723',
    authDomain: 'website-192723.firebaseapp.com',
    databaseURL: 'https://website-192723.firebaseio.com',
    storageBucket: 'website-192723.appspot.com',
  );
}
