// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_MiTag5W3b-bf0eVqCYJeBW6EDcTSps',
    appId: '1:988796995940:web:2acac374a827efeb94d271',
    messagingSenderId: '988796995940',
    projectId: 'pola-67584',
    authDomain: 'pola-67584.firebaseapp.com',
    storageBucket: 'pola-67584.firebasestorage.app',
    measurementId: 'G-WHVEL4SD48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbTmV3E2NzUboxSamZ6uHUq2AIllxrAPY',
    appId: '1:988796995940:android:76807c6d06531f3b94d271',
    messagingSenderId: '988796995940',
    projectId: 'pola-67584',
    storageBucket: 'pola-67584.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0z_MybmM81fqRej8cLMs8gAwFlfJwIC8',
    appId: '1:988796995940:ios:b78a21a4fe982b0494d271',
    messagingSenderId: '988796995940',
    projectId: 'pola-67584',
    storageBucket: 'pola-67584.firebasestorage.app',
    iosBundleId: 'co.tz.pola.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0z_MybmM81fqRej8cLMs8gAwFlfJwIC8',
    appId: '1:988796995940:ios:1c96e44a24abf3a394d271',
    messagingSenderId: '988796995940',
    projectId: 'pola-67584',
    storageBucket: 'pola-67584.firebasestorage.app',
    iosBundleId: 'co.tz.pola.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt_MiTag5W3b-bf0eVqCYJeBW6EDcTSps',
    appId: '1:988796995940:web:171b15113103694794d271',
    messagingSenderId: '988796995940',
    projectId: 'pola-67584',
    authDomain: 'pola-67584.firebaseapp.com',
    storageBucket: 'pola-67584.firebasestorage.app',
    measurementId: 'G-3C4DK7K4G8',
  );
}
