# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

# --- Fix for gRPC + Xcode compatibility (Firebase requires gRPC ~> 1.62) ---
pod 'gRPC-C++', '1.62.5'
pod 'gRPC-Core', '1.62.5'
pod 'abseil', '1.20240116.2'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Fix SDWebImage compatibility issue
  pod 'SDWebImage', '~> 5.15.0'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# # post_install do |installer|
# #   installer.pods_project.targets.each do |target|
# #     flutter_additional_ios_build_settings(target)
    
#     # Fix for SDWebImage compilation issues and Firebase requirements
#     target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#         '$(inherited)',
#         'PERMISSION_CAMERA=1',
#         'PERMISSION_PHOTOS=1',
#         'PERMISSION_MEDIA_LIBRARY=1',
#         'PERMISSION_LOCATION=1',
#       ]
      
#       # Fix for BoringSSL-GRPC: Remove -Gw flag that causes simulator build issues
#       if target.name == 'BoringSSL-GRPC'
#         config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Wno-unreachable-code -Wno-comma -Wno-shorten-64-to-32"
#       end
#     end
#   end
# end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_MEDIA_LIBRARY=1',
        'PERMISSION_LOCATION=1',
      ]
      
      # Force C++17 for all targets (Xcode requirement)
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
    end
  end
end
